name: Terraform Deploy

on:
  push:
    branches: ["main"]
  
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  AWS_S3_ENDPOINT: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - run: tofu init -backend-config="bucket=${{ secrets.S3_BUCKET }}" -backend-config="key='free-domains/key.tfstate'"
      - run: tofu apply -var='zones=${{ vars.ZONES }}' -auto-approve
